[features]
seeds = false
skip-lint = false
[programs.localnet]
bridge_solana = "Nq7BKR8NUodEcmKmWnSfi3sxTnZGPHgtLynvzdki8fm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/user0/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
